#include <QFile>

#include "stylesheet.h"

Stylesheet::Stylesheet()
{
    this->initializeStylesheet();
}

void Stylesheet::initializeStylesheet()
{
    QFile smiley                (":/stylesheet/infobar_smiley.css");
    QFile smiley_won            (":/stylesheet/infobar_smiley_won.css");
    QFile smiley_lost           (":/stylesheet/infobar_smiley_lost.css");
    QFile smiley_surprised      (":/stylesheet/infobar_smiley_surprised.css");
    QFile button_1              (":/stylesheet/button_1.css");
    QFile button_2              (":/stylesheet/button_2.css");
    QFile button_3              (":/stylesheet/button_3.css");
    QFile button_4              (":/stylesheet/button_4.css");
    QFile button_5              (":/stylesheet/button_5.css");
    QFile button_6              (":/stylesheet/button_6.css");
    QFile button_7              (":/stylesheet/button_7.css");
    QFile button_8              (":/stylesheet/button_8.css");
    QFile button_revealed       (":/stylesheet/button_revealed.css");
    QFile button_unrevealed     (":/stylesheet/button_unrevealed.css");
    QFile button_pressed        (":/stylesheet/button_pressed.css");
    QFile button_mine           (":/stylesheet/button_mine.css");
    QFile button_mine_hit       (":/stylesheet/button_mine_hit.css");
    QFile button_flag           (":/stylesheet/button_flag.css");
    QFile digital_0             (":/stylesheet/digital_0.css");
    QFile digital_1             (":/stylesheet/digital_1.css");
    QFile digital_2             (":/stylesheet/digital_2.css");
    QFile digital_3             (":/stylesheet/digital_3.css");
    QFile digital_4             (":/stylesheet/digital_4.css");
    QFile digital_5             (":/stylesheet/digital_5.css");
    QFile digital_6             (":/stylesheet/digital_6.css");
    QFile digital_7             (":/stylesheet/digital_7.css");
    QFile digital_8             (":/stylesheet/digital_8.css");
    QFile digital_9             (":/stylesheet/digital_9.css");
    smiley.open                 (QFile::ReadOnly);
    smiley_won.open             (QFile::ReadOnly);
    smiley_lost.open            (QFile::ReadOnly);
    smiley_surprised.open       (QFile::ReadOnly);
    button_1.open               (QFile::ReadOnly);
    button_2.open               (QFile::ReadOnly);
    button_3.open               (QFile::ReadOnly);
    button_4.open               (QFile::ReadOnly);
    button_5.open               (QFile::ReadOnly);
    button_6.open               (QFile::ReadOnly);
    button_7.open               (QFile::ReadOnly);
    button_8.open               (QFile::ReadOnly);
    button_revealed.open        (QFile::ReadOnly);
    button_unrevealed.open      (QFile::ReadOnly);
    button_pressed.open         (QFile::ReadOnly);
    button_mine.open            (QFile::ReadOnly);
    button_mine_hit.open        (QFile::ReadOnly);
    button_flag.open            (QFile::ReadOnly);
    digital_0.open              (QFile::ReadOnly);
    digital_1.open              (QFile::ReadOnly);
    digital_2.open              (QFile::ReadOnly);
    digital_3.open              (QFile::ReadOnly);
    digital_4.open              (QFile::ReadOnly);
    digital_5.open              (QFile::ReadOnly);
    digital_6.open              (QFile::ReadOnly);
    digital_7.open              (QFile::ReadOnly);
    digital_8.open              (QFile::ReadOnly);
    digital_9.open              (QFile::ReadOnly);
    this->smiley                = QLatin1String(smiley.readAll());
    this->smiley_won            = QLatin1String(smiley_won.readAll());
    this->smiley_lost           = QLatin1String(smiley_lost.readAll());
    this->smiley_surprised      = QLatin1String(smiley_surprised.readAll());
    this->button_1              = QLatin1String(button_1.readAll());
    this->button_2              = QLatin1String(button_2.readAll());
    this->button_3              = QLatin1String(button_3.readAll());
    this->button_4              = QLatin1String(button_4.readAll());
    this->button_5              = QLatin1String(button_5.readAll());
    this->button_6              = QLatin1String(button_6.readAll());
    this->button_7              = QLatin1String(button_7.readAll());
    this->button_8              = QLatin1String(button_8.readAll());
    this->button_revealed       = QLatin1String(button_revealed.readAll());
    this->button_unrevealed     = QLatin1String(button_unrevealed.readAll());
    this->button_pressed        = QLatin1String(button_pressed.readAll());
    this->button_mine           = QLatin1String(button_mine.readAll());
    this->button_mine_hit       = QLatin1String(button_mine_hit.readAll());
    this->button_flag           = QLatin1String(button_flag.readAll());
    this->digital_0             = QLatin1String(digital_0.readAll());
    this->digital_1             = QLatin1String(digital_1.readAll());
    this->digital_2             = QLatin1String(digital_2.readAll());
    this->digital_3             = QLatin1String(digital_3.readAll());
    this->digital_4             = QLatin1String(digital_4.readAll());
    this->digital_5             = QLatin1String(digital_5.readAll());
    this->digital_6             = QLatin1String(digital_6.readAll());
    this->digital_7             = QLatin1String(digital_7.readAll());
    this->digital_8             = QLatin1String(digital_8.readAll());
    this->digital_9             = QLatin1String(digital_9.readAll());
    smiley.close();
    smiley_won.close();
    smiley_lost.close();
    smiley_surprised.close();
    button_1.close();
    button_2.close();
    button_3.close();
    button_4.close();
    button_5.close();
    button_6.close();
    button_7.close();
    button_8.close();
    button_revealed.close();
    button_unrevealed.close();
    button_pressed.close();
    button_mine.close();
    button_mine_hit.close();
    button_flag.close();
    digital_0.close();
    digital_1.close();
    digital_2.close();
    digital_3.close();
    digital_4.close();
    digital_5.close();
    digital_6.close();
    digital_7.close();
    digital_8.close();
    digital_9.close();
}
